#
# Module manifest for module 'Set-Wallpaper'
#
# Generated by: feder
#
# Generated on: 4/9/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FP.SetWallpaper.dll'

# Version number of this module.
ModuleVersion = '1.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module
GUID = '8bb87501-8d54-4083-8fd5-3fce5ee2d1b5'

# Author of this module
Author = 'federico-paolillo'

# Copyright statement for this module
Copyright = '(c) 2020 federico-paolillo. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Cmdlets for wallpaper manipulation on Windows 10 x64'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'Amd64'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @("FP.SetWallpaper.COM.dll")

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @("Get-Monitor", "Get-Wallpaper", "Set-Wallpaper")

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Windows', 'PSEdition_Core', 'PSEdition_Desktop')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/federico-paolillo/set-wallpaper/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/federico-paolillo/set-wallpaper'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $true

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

